### PR TITLE
Replace " with &quot; in addon.xml

### PR DESCRIPTION
**Pull request by gade01**
This replaces `"` with `&quot;` for translations in addon.xml

Please close https://github.com/xbmc/visualization.waveform/pull/41 before merging this PR.

### CODE REVIEW

**Review by AlwinEsch — APPROVED** [review]
Have the other request closed

**Comment by gade01** [comment]
Thanks a lot.
Feel free to merge this one.

Then the workflow will create a correct PR to copy metadata to the language files.

**Comment by AlwinEsch** [comment]
Think delete of other https://github.com/xbmc/visualization.waveform/pull/44 where recreated, must be short before this comes in?

**Comment by gade01** [comment]
The workflow will run every time a language file is changed.
So the workflow ran again when https://github.com/xbmc/visualization.waveform/pull/42 were merged.

It will run again correctly when this PR is merged.

**Pull request merged**
