### PR TITLE
support darwin_embedded define

### PR DESCRIPTION
**Pull request by phunkyfish**
xbmc/xbmc#16039

Merged if/when the above PR is merged into kodi master

### CODE REVIEW

**Comment by Rechi** [comment]
Master branch is no longer used, current active branch is Leia.

**Comment by phunkyfish** [comment]
Does this mean that after https://github.com/xbmc/xbmc/pull/16039 is merged we need to add a Matrix branch all binary addons? Or some change to that effect?

Otherwise it will build for Matrix but never again for Leia.

**Comment by Rechi** [comment]
think about how the condition can be adjusted that it is valid for Leia and Matrix (after the CORE_SYSTEM_NAME change)

**Comment by phunkyfish** [comment]
Something like this would work:

```
if(NOT CORE_SYSTEM_NAME STREQUAL darwin_embedded AND NOT CORE_SYSTEM_NAME STREQUAL ios)
```

**Comment by Rechi** [comment]
yes

**Pull request merged**
