### PR TITLE
[debian packaging] reband to kodi and fix install paths

### PR DESCRIPTION
**Pull request by wsnipex**
this has been forgotten...

### CODE REVIEW

**Comment by notspiff** [comment]
Apparently i am no longer upstream for this one.

**Comment by notspiff** [comment]
tbh i think it would be less frustrating to point the repo at your or my fork. not sure if afedchin is responsive enough..

**Comment by wsnipex** [comment]
absolutely, no idea why you are not upstream anymore
@Montellese ping

**Comment by Montellese** [comment]
It was probably initially done for testing/development as part of the PR and then nobody sent the changes upstream and just pointed to whatever repository was used for the platform specific development. I'm fine with giving this back to whoever is willing to maintain it.

**Comment by notspiff** [comment]
then i will make sure my forks are up to date (i'll rebase anything that is unique to my forks), then send a pull to point to mine. okay ?

**Comment by wsnipex** [comment]
can you pick the packaging changes or want me to rebase?

**Comment by notspiff** [comment]
i'll pick no problem.

**Comment by Montellese** [comment]
@notspiff: sounds good and sorry for the hassle.

**Comment by notspiff** [comment]
picked, closing this.

**Pull request closed without merging**
